# Generated by Django 3.1 on 2021-06-27 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('project_des', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_des', to='app.projectname')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientsQuestion',
        ),
        migrations.RemoveField(
            model_name='client',
            name='salary',
        ),
    ]
