# Generated by Django 3.1 on 2021-06-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210627_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectname',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
